export const data = [
  { name: "Julie", dept: "Legal", gender: "Male" },
  { name: "Onfroi", dept: "Accounting", gender: "Male" },
  { name: "Bevan", dept: "Legal", gender: "Male" },
  { name: "Broddie", dept: "Sales", gender: "Male" },
  { name: "Richard", dept: "Business Development", gender: "Non-binary" },
  { name: "Early", dept: "Legal", gender: "Male" },
  { name: "Francisco", dept: "Training", gender: "Male" },
  { name: "Allin", dept: "Business Development", gender: "Male" },
  { name: "Garvey", dept: "Accounting", gender: "Male" },
  { name: "Fedora", dept: "Product Management", gender: "Female" },
  { name: "Ketti", dept: "Research and Development", gender: "Female" },
  { name: "Dominga", dept: "Engineering", gender: "Bigender" },
  { name: "Dilly", dept: "Human Resources", gender: "Male" },
  { name: "Lucille", dept: "Sales", gender: "Female" },
  { name: "Inigo", dept: "Support", gender: "Male" },
  { name: "Denys", dept: "Services", gender: "Male" },
  { name: "Renelle", dept: "Research and Development", gender: "Female" },
  { name: "Matthieu", dept: "Engineering", gender: "Male" },
  { name: "Rowena", dept: "Legal", gender: "Female" },
  {
    name: "Beatrice",
    dept: "Research and Development",
    gender: "Female",
  },
  { name: "Kessiah", dept: "Services", gender: "Female" },
  { name: "Seymour", dept: "Marketing", gender: "Male" },
  { name: "Madelena", dept: "Training", gender: "Female" },
  { name: "Sylvia", dept: "Legal", gender: "Female" },
  { name: "Ray", dept: "Research and Development", gender: "Male" },
  { name: "Zondra", dept: "Research and Development", gender: "Female" },
  { name: "Blakelee", dept: "Training", gender: "Female" },
  { name: "Mathian", dept: "Legal", gender: "Male" },
  { name: "Belia", dept: "Product Management", gender: "Female" },
  { name: "Bennie", dept: "Engineering", gender: "Female" },
  { name: "Ruy", dept: "Business Development", gender: "Non-binary" },
  { name: "Case", dept: "Product Management", gender: "Male" },
  { name: "Gill", dept: "Sales", gender: "Female" },
  { name: "Rancell", dept: "Research and Development", gender: "Male" },
  { name: "Gerrie", dept: "Marketing", gender: "Female" },
  { name: "Munroe", dept: "Support", gender: "Male" },
  { name: "Nessa", dept: "Research and Development", gender: "Female" },
  { name: "Lanae", dept: "Support", gender: "Female" },
  { name: "Gilbert", dept: "Human Resources", gender: "Male" },
  { name: "Innis", dept: "Human Resources", gender: "Male" },
  { name: "Percy", dept: "Accounting", gender: "Male" },
  { name: "Hervey", dept: "Support", gender: "Male" },
  { name: "Ingrid", dept: "Engineering", gender: "Female" },
  { name: "Minor", dept: "Marketing", gender: "Male" },
  { name: "Leopold", dept: "Legal", gender: "Male" },
  { name: "Freddie", dept: "Training", gender: "Female" },
  {
    name: "Iolande",
    dept: "Research and Development",
    gender: "Genderfluid",
  },
  { name: "Nettie", dept: "Accounting", gender: "Female" },
  { name: "Chris", dept: "Marketing", gender: "Male" },
  { name: "Brinn", dept: "Human Resources", gender: "Female" },
  { name: "Shalom", dept: "Services", gender: "Male" },
  { name: "Sonni", dept: "Research and Development", gender: "Female" },
  { name: "Gay", dept: "Engineering", gender: "Female" },
  { name: "Gradeigh", dept: "Legal", gender: "Male" },
  { name: "Von", dept: "Legal", gender: "Male" },
  { name: "Stanislaw", dept: "Support", gender: "Male" },
  { name: "Doris", dept: "Accounting", gender: "Female" },
  { name: "Biddy", dept: "Product Management", gender: "Female" },
  { name: "Ambur", dept: "Support", gender: "Female" },
  { name: "Nikoletta", dept: "Legal", gender: "Agender" },
  { name: "Jesus", dept: "Services", gender: "Genderfluid" },
  { name: "Benedicto", dept: "Product Management", gender: "Male" },
  { name: "Patrizius", dept: "Marketing", gender: "Male" },
  { name: "Ketti", dept: "Support", gender: "Female" },
  { name: "Arin", dept: "Training", gender: "Male" },
  { name: "Sheffie", dept: "Engineering", gender: "Male" },
  { name: "Filmer", dept: "Sales", gender: "Male" },
  { name: "Simeon", dept: "Human Resources", gender: "Male" },
  { name: "Randi", dept: "Human Resources", gender: "Male" },
  { name: "Sax", dept: "Research and Development", gender: "Male" },
  { name: "Britt", dept: "Training", gender: "Male" },
  { name: "Jerad", dept: "Research and Development", gender: "Male" },
  { name: "Vale", dept: "Product Management", gender: "Male" },
  { name: "Teodora", dept: "Product Management", gender: "Female" },
  { name: "Geoff", dept: "Support", gender: "Male" },
  { name: "Tiebout", dept: "Services", gender: "Male" },
  { name: "Emelen", dept: "Research and Development", gender: "Male" },
  { name: "Byrom", dept: "Product Management", gender: "Male" },
  { name: "Garey", dept: "Business Development", gender: "Male" },
  { name: "Florette", dept: "Business Development", gender: "Female" },
  { name: "Emeline", dept: "Legal", gender: "Female" },
  { name: "Barclay", dept: "Human Resources", gender: "Agender" },
  { name: "Angie", dept: "Services", gender: "Female" },
  { name: "Padget", dept: "Human Resources", gender: "Genderfluid" },
  { name: "Aleksandr", dept: "Research and Development", gender: "Male" },
  { name: "Valma", dept: "Engineering", gender: "Female" },
  { name: "Reinald", dept: "Legal", gender: "Male" },
  { name: "Linnie", dept: "Business Development", gender: "Female" },
  { name: "Woodman", dept: "Services", gender: "Non-binary" },
  { name: "Gray", dept: "Business Development", gender: "Male" },
  { name: "Faunie", dept: "Legal", gender: "Female" },
  { name: "Georgie", dept: "Human Resources", gender: "Female" },
  { name: "Wandis", dept: "Human Resources", gender: "Female" },
  { name: "Terri", dept: "Services", gender: "Male" },
  { name: "Lutero", dept: "Sales", gender: "Male" },
  { name: "Christoper", dept: "Training", gender: "Male" },
  { name: "Brenn", dept: "Engineering", gender: "Female" },
  { name: "Niall", dept: "Services", gender: "Male" },
  { name: "Ruy", dept: "Sales", gender: "Male" },
  { name: "Tanner", dept: "Sales", gender: "Male" },
];
